import json
constraintlist=[
        {'id': 0,'constraint': 'enforce_icu_week_same_person','startdate': '2022-05-30',
        'enddate': '2022-12-01'},
        {'id': 1,
            'constraint': 'enforce_weekend_same_person',
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 2,
            'constraint': 'enforce_weekend_not_following_week',
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 3,
            'constraint': 'enforce_acceptable_deviation',
            'shift': 'wddt',
            'deviation': 8,
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 4,
            'constraint': 'enforce_acceptable_deviation',
            'shift': 'wdoc',
            'deviation': 5,
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 5,
            'constraint': 'enforce_acceptable_deviation',
            'shift': 'weoc',
            'deviation': 5,
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 6,
         'constraint': 'enforce_acceptable_deviation',
            'shift': 'wedt',
            'deviation': 6,
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 7,
         'constraint': 'balance_tallies',
            'startdate': '2022-04-04',
            'enddate': '2022-12-01'},

        {'id': 8,
         'constraint': 'enforce_no_multiple_weekday_calls',
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 9, 'constraint': 'enforce_no_night_before_dcc',
         'startdate': '2022-05-30',
         'enddate': '2022-12-01'},
        {'id': 10,
         'constraint': 'enforce_no_monday_after_weekend',
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 11,
         'constraint': 'enforce_max_x_in_y_weekends',
            'numerator': 1,
            'denominator': 2,
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 12,
         'constraint': 'enforce_max_x_in_y_weekends',
            'numerator': 2,
            'denominator': 6,
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 13,
         'constraint': 'enforce_max_x_in_y_weekends',
            'numerator': 3,
            'denominator': 9,
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 14,
         'constraint': 'enforce_max_x_in_y_weeks',
            'numerator': 1,
            'denominator': 3,
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 15,
         'constraint': 'enforce_max_x_oncalls_in_y_days',
            'numerator': 4,
            'denominator': 12,
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'},
        {'id': 16,
         'constraint': 'limit_locum_shifts',
            'shifttype': 'ANY',
            'staff': 'RORY',
            'maximum': 0,
            'startdate': '2022-05-30', 'enddate': '2022-12-01'},
        {'id': 17,
         'constraint': 'limit_locum_shifts',
            'staff': 'BARTEK',
            'minimum': 2,
            'startdate': '2022-05-30',
            'enddate': '2022-12-01'}
    ]

with open('constraintslist.txt','w',encoding='utf-8') as f:
    for c in constraintlist:
        f.write(json.dumps(c))
        f.write('\n')